### ISSUE TITLE
兄弟我安装遇到问题了 不知道可否留个联系方式?

### ISSUE THREAD

**Issue by 0x1ng** [pizepei/LayuiAdminProPHP#1]
兄弟我安装遇到问题了 不知道可否留个联系方式?

**Comment by pizepei** [comment]
邮箱pizepei@pizepei.com

**Comment by pizepei** [comment]
qq 848733913




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "0x1ng"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 晚上6:26
收件人: "pizepei/LayuiAdminProPHP"<LayuiAdminProPHP@noreply.github.com&gt;; 
抄送: "边际浮华"<848733913@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [pizepei/LayuiAdminProPHP] 兄弟我安装遇到问题了 不知道可否留个联系方式? (#1)




Closed #1.
